Feat/amino input v3
amino-ui/core pull request #195
Opened 2022-03-21 15:55 UTC by Thienhuynh95

## Jira issue

[Updates to form component designs](https://myzonos.atlassian.net/browse/BBT-464
## Description

This PR styles number, search & password input type

2022-03-21 15:56 UTC, goodpickle commented
@Thienhuynh95 Looks like there is a merge conflict to resolve

2022-03-21 16:12 UTC, Thienhuynh95 commented
@goodpickle I've just merged and fixed the conflict, can you please check again!

2022-03-21 16:15 UTC, goodpickle requested changes
Most of my suggestions are just general cleanup for code that was copied and pasted.

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/SearchInput.tsx
> +        pattern={pattern && pattern}
```suggestion
        pattern={pattern}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/SearchInput.tsx
> +        tabIndex={tabIndex && tabIndex}
```suggestion
        tabIndex={tabIndex}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/InputType/FloatLabelInput.tsx
> +          tabIndex={tabIndex && tabIndex}
```suggestion
          tabIndex={tabIndex}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/InputType/FloatLabelInput.tsx
> +          pattern={pattern && pattern}
```suggestion
          pattern={pattern}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/InputType/FloatLabelInput.tsx
> +          onKeyDown={onKeyDown && onKeyDown}
```suggestion
          onKeyDown={onKeyDown}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/InputType/FloatLabelInput.tsx
> +          autoFocus={autoFocus && autoFocus}
```suggestion
          autoFocus={autoFocus}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/InputType/FloatLabelInput.tsx
> +  placeholder?: string;
Let's chat about this one. I would expect `placeholder` to be the best name for the text that is displayed in the input.

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/InputType/FloatLabelInput.tsx
> +          readOnly={readOnly || false}
```suggestion
          readOnly={readOnly}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/InputType/FloatLabelInput.tsx
> +          required={required || false}
```suggestion
          required={required}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/InputType/NumberInput.tsx
> +        readOnly={readOnly || false}
```suggestion
        readOnly={readOnly}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/InputType/PasswordInput.tsx
> +        readOnly={readOnly || false}
```suggestion
        readOnly={readOnly}
```

2022-03-21 16:15 UTC, goodpickle commented on src/components/Input/SearchInput.tsx
> +        readOnly={readOnly || false}
```suggestion
        readOnly={readOnly}
```

2022-03-21 16:15 UTC, goodpickle commented on src/icons/IconBase copy.tsx
> +
This component filename is `IconBase copy.tsx`

I'm guessing it is a file that needs to be removed or renamed. 🤓

2022-03-22 21:51 UTC, goodpickle approved these changes
Looks good. Let's chat about another solution instead of a `Link` button at some point.

2022-03-22 21:53 UTC, Thienhuynh95 commented on src/components/Button/Link.tsx
> +    padding: 0;
Gotcha, do you want me to move `Link` component from `dashboard-web` over?

2022-03-22 21:54 UTC, goodpickle commented on src/components/Button/Link.tsx
> +    padding: 0;
No. I don't know what to do about it. I need to brainstorm on it. Probably come up with a different component name for this one.

2022-03-23 15:26 UTC, merged