Style/rich radio and table row
amino-ui/core pull request #452
Opened 2023-04-05 22:00 UTC by Thienhuynh95

## Description

This PR:
- adds no hover state for table row (will not change the background when hovering)
- adds small size RichRadio of each item and stories as new design of quotes page has it.
- 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/17950626/230221489-be4ab02e-f744-49c2-84e9-2eea06af3b21.png">
<img width="763" alt="image" src="https://user-images.githubusercontent.com/17950626/230221412-1cfa1ba0-96f7-4169-8bd9-7c996e0695bc.png">

## Todo

- [ ] Bump version and add tag

2023-04-05 22:04 UTC, goodpickle requested changes

2023-04-05 22:04 UTC, goodpickle commented on src/components/rich-radio/RichRadio.tsx
> +   * @default 40
```suggestion
   * @param itemHeight
   * @default 40
```

2023-04-06 14:27 UTC, goodpickle submitted a review, later dismissed

2023-04-06 15:29 UTC, evad1n approved these changes

2023-04-06 15:35 UTC, merged